### ISSUE TITLE
Complete prompt to extract implicit knowledge

### ISSUE THREAD

**Issue by Richar-Du** [guilk/KAT#10]
Hi,
Thanks for your awesome work! Would you mind providing the code to prompt gpt-3 or the complete prompt to extract implicit knowledge? I notice in Figure 7 in your paper, only part of the prompt are displayed as an example. 
By the way, are all questions have the same prompts?
I'm looking forward to your reply, thanks in advance :)

**Comment by guilk** [comment]
Hi,

Thanks for your interest in our work. We actually follow [PICa](https://github.com/microsoft/PICa) to prompt GPT-3. I think they have provided the code and template. We use the same prompts for all the questions. 

We only prompt GPT-3 once using the same template to get the candidate answer and its evidence. It may be helpful if you can prompt GPT-3 with different templates.

**Comment by Richar-Du** [comment]
Thanks for your help, I will turn to check PICa.
