### ISSUE TITLE
Source code for wikidata pre-processing

### ISSUE THREAD

**Issue by CrystalSusie** [guilk/KAT#12]
Hello, thanks for the excellent work!
How can I get the content in wikidata_ontology.pkl from raw wikidata file (wikidata-20210920-all.json)? Could you please release the code for the original pre-processing step?

**Comment by guilk** [comment]
Hi, can you check the [folder](https://github.com/guilk/KAT/releases/tag/metadata). 

To pre-process the data, you can use the script build_wikidata_entity_db.py. Basically, you use a sliding window to crop images and retrieve entities from Wikidata.
