### ISSUE TITLE
sparql to extract wikidata_ontology.pkl?

### ISSUE THREAD

**Issue by sanghapark** [guilk/KAT#14]
Hi, thank you for the great work.
can you share sparql to extract wikidata_ontology.pkl?
also, on [Wikidata Query Service](https://query.wikidata.org/), it crashes when the result is too big. How did you extract?
thank you!

**Comment by guilk** [comment]
Sorry, I did not save the sparql commands. As far as I can remember, there seemed to be some difference between instances and classes. I did not use instances which reduced the number of retrieved entities. 

Also, I dumped one copy of Wikidata to my local disk to build my wikidata ontology list.
