### ISSUE TITLE
the number of entities

### ISSUE THREAD

**Issue by Su1008** [guilk/KAT#2]
Excuse me, the number of entities in the wikidata_ontology.pkl  you released is different from that in the paper

**Comment by guilk** [comment]
Yeah, as mentioned in our paper, we removed the entities if their labels or descriptions are empty.

**Comment by Su1008** [comment]
it remains 423,520 entity triplets after filting. But in this  wikidata_ontology.pkl, only 187308.
![Snipaste_2022-07-08_21-03-41](https://user-images.githubusercontent.com/48051151/177997522-751e286b-bb32-40be-8862-b50d6800385f.png)

**Comment by guilk** [comment]
Sorry that there are 423k entities before filtering. A lot of them have empty labels or descriptions. This is a mistake in our paper. I believe this will not make a huge difference if you want to add more entities to it. You can use sparql to create your own knowledge base。
