### ISSUE TITLE
the question of code in build_wikidata_entity_db.py

### ISSUE THREAD

**Issue by Su1008** [guilk/KAT#5]
Excuse me. Is this code right?  why use the variable  of top_ids_and_scores in the loop？ it means the result same
![image](https://user-images.githubusercontent.com/48051151/178254852-304663d8-33c3-448d-aa20-fa57eda7c1fd.png)

**Comment by guilk** [comment]
Yeah, I use this script to retrieve entities. I have not cleaned this up so you may need to go through it line by line to check the results.
