### ISSUE TITLE
Source code for the pre-processing step

### ISSUE THREAD

**Issue by duong-tr** [guilk/KAT#7]
Hello,

Thanks for the amazing work.
Could you please release the code for the pre-processing step?

**Comment by guilk** [comment]
Hi,

What do you mean by preprocessing? To extract the explicit knowledge, could you check [build_wikidata_entity_db.py](https://github.com/guilk/KAT/blob/main/build_wikidata_entity_db.py)? For the implicit knowledge, you many need to refer to [PICa](https://arxiv.org/abs/2109.05014)

**Comment by duong-tr** [comment]
> Hi,
> 
> What do you mean by preprocessing? To extract the explicit knowledge, could you check [build_wikidata_entity_db.py](https://github.com/guilk/KAT/blob/main/build_wikidata_entity_db.py)? For the implicit knowledge, you many need to refer to [PICa](https://arxiv.org/abs/2109.05014)

Hi,

Thanks for your quick response.
I would like to extract the pre-processed data for another VQA dataset, which is similar to what you did with OK-VQA in the "Pre-processed Data" section from your README.
Should it be enough to follow your comment?

**Comment by guilk** [comment]
Yes, it should be enough to exact implicit/explicit knowledge based on our provided code.

**Comment by duong-tr** [comment]
> Yes, it should be enough to exact implicit/explicit knowledge based on our provided code.

Thank you.
