### ISSUE TITLE
About wikidata

### ISSUE THREAD

**Issue by Su1008** [guilk/KAT#8]
Excuse me, Why retrieving role objects through the SPARQL only has 120 records.
![Snipaste_2022-10-03_17-03-40](https://user-images.githubusercontent.com/48051151/193540019-c457c850-6f70-4a06-9340-651a1ea112cc.png)

**Comment by guilk** [comment]
Hi, as far as I can remember, there is a difference between "instance of/P31" and "subclass of/P279". You may need to use P279 instead of P31. Or you can use both and merge the results together.

**Comment by Su1008** [comment]
Sorry，I have used P279 instead of P31, but it only 35 records. 
Please where am I doing wrong?
![image](https://user-images.githubusercontent.com/48051151/193716998-9d1572f4-a85b-43e8-b67a-787eee034719.png)

**Comment by guilk** [comment]
Hi, you need to use * in the query to indicate "any number of subclasses". Try "wdt:P279*" instead of "wdt:P31".

**Comment by Su1008** [comment]
thanks. solved.
