### ISSUE TITLE
In the index.py file, where can I get the "index.faiss" and "index_meta.dpr"?

### ISSUE THREAD

**Issue by LIMANONDBannapol** [guilk/KAT#9]
Thank you for your amazing work and contributing to the community. I have one question. In the index.py file, where can I get the "index.faiss" and "index_meta.dpr"?

**Comment by guilk** [comment]
Hi, you need to build these two files based on your tasks.  Check this [line](https://github.com/guilk/KAT/blob/bb13c3512819fd5f43b7191c767f6d66ae09c158/build_wikidata_entity_db.py#L73)

**Comment by LIMANONDBannapol** [comment]
Thank you so much for your response. 🙏🙏🙏

**Comment by kebijuelun** [comment]
Hi, thanks for the great work, could you please give me some example for using `extract_features` function？ I have not seen any function call in this repo

@LIMANONDBannapol  @guilk
